---
- name: create group nginx-exp
  become: true
  group:
    name: "{{ nginx_group }}"
    state: present
- name: create group nginx-exp
  become: true
  user:
    name: "{{ nginx_user }}"
    state: present
    group: nginx-exp

- name: Create an insecure file
  become: true
  file:
    path: /prometheus
    owner: root
    group: root
    mode: '1777'

- name: Download prometheus Conf
  get_url:
    url: https://github.com/nginxinc/nginx-prometheus-exporter/releases
    dest: /prometheus
    mode: '0440'

- name: Unarchive a file that is already on the remote machine
  unarchive:
    src: /prometheus/nginx-prometheus-exporter
    dest: /usr/local/bin/
    remote_src: true

- name: Template a file to /etc/files.conf
  become: true
  template:
    src: nginx-exporter.j2
    dest: /etc/systemd/system/
    mode: '0644'
