---
- name: get nginx rpmkey
  become: true
  rpm_key:
    key: "{{ nginx_signing_key }}"

- name: add nginx repository
  become: true
  yum_repository:
    name: nginx
    baseurl: "{{ nginx_base_repository }}"
    description: nginx repository
    enabled: true
    gpgcheck: true

- name: install nginx
  become: true
  package:
    name: nginx
    state: present
  notify: start nginx

- name: override default home page
  become: true
  copy:
    content: |
      <!DOCTYPE html>
      <html>
      <head>
        <title>Hello world.</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style>body {font: normal 18px Arial; margin: 4em;}</style>
      </head>
      <body>
        <p>
          YAML supports multi-line blocks using specific indicators.<br />
          Read more at
          <a href="https://yaml-multiline.info">YAML-multiline.info</a>.
        </p>
      </body>
      </html>
    dest: /usr/share/nginx/html/index.html

- name: Check that a page returns a status 200 and fail if the word AWESOME is not in the page contents
  uri:
    url: http://localhost
    method: GET
    return_content: yes
  register: site
  failed_when: site.status != 200

- name: Check and Fail if 9113/metrics does not return nginx_up 1
  uri:
    url: http://localhost:9113/metrics
    method: GET
    return_content: yes
  register: this
  failed_when: "'nginx_up 1' not in this.content"

- include: exporter.yml
